Space group
femtobit/netket pull request #2
Opened 2021-04-02 22:24 UTC by chrisrothUT

I implemented rotations on the grid using the SymmGroup class. Right now "rotations" just takes the outer product of all possible planar rotations. For ndim > 2, I need to implement a method of pruning duplicates.

2021-04-06 08:03 UTC, femtobit requested changes
Looks good, thanks! Just one point regarding the `__init__`s, otherwise we can merge this quickly and discuss the rest in the main NetKet PR.

2021-04-06 08:03 UTC, femtobit commented on netket/graph/grid.py
> +class Planar_Rotation(Element):
```suggestion
class PlanarRotation(Element):
```

2021-04-06 08:03 UTC, femtobit commented on netket/graph/grid.py
> +
Since this is a [`@dataclass`](https://docs.python.org/3/library/dataclasses.html), it probably should not have a custom `__init__`. (I was mainly using dataclasses here because they give a useful constructor and equality comparison by default.) Instead, the attributes should be specified like this (the code calling the constructor needs to be modified as well since this replaces `info` with two separate parameters):
```suggestion
    num_quarter_rots: int
    axes: Tuple[int]
    dims: Tuple[int]
```

2021-04-06 08:03 UTC, femtobit commented on netket/graph/grid.py
> +        rotations = [Planar_Rotation(el, dims) for el in rotations]
```suggestion
        rotations = [PlanarRotation(el, dims) for el in rotations]
```

2021-04-06 08:03 UTC, femtobit commented on netket/graph/grid.py
> +        self.dims = dims
Same as above: Remove constructor and use dataclass attributes.

2021-04-06 08:15 UTC, femtobit commented on netket/graph/grid.py
> +@dataclass
Just noticed that myself: Elements that are `dataclass`es should be frozen (that is, immutable) in order to have a well-defined hash.

On the positive side, if `frozen=True` is passed, the `__hash__` method is created automatically.

```suggestion
@dataclass(frozen=True)
```

2021-04-06 08:15 UTC, femtobit commented on netket/graph/grid.py
> +        return hash((self.num_quarter_rots, self.axes, self.dims))
```suggestion
```

2021-04-06 08:15 UTC, femtobit commented on netket/graph/grid.py
> +@dataclass
```suggestion
@dataclass(frozen=True)
```

2021-04-06 08:15 UTC, femtobit commented on netket/graph/grid.py
> +        return hash((self.reflect, self.axis, self.dims))
```suggestion
```

2021-04-06 15:13 UTC, femtobit commented
Hm, I've tried it on a 3x3 grid and get some results that look incorrect to me (or am I just confused about the indices?). I'd expect, e.g.,
```python3
>>> g = nk.graph.Grid([3, 3])
>>> r1 = g.space_group()[1]
>>> r1
RF(π,-1) #  reflection along y
>>> r1(np.arange(9)).reshape(3, 3)
# Expected:
array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])
```
but instead
```python
>>> r1(np.arange(9)).reshape(3, 3)
array([[0, 2, 1],
       [3, 5, 4],
       [6, 8, 7]])
```
which is neither a reflection nor rotation as far as I can tell (as those cannot map a corner vertex like `2` to be at the center of a side).

2021-04-06 15:49 UTC, chrisrothUT commented
Hi, 

No it's a dumb mistake on my part. I was thinking about lattices with PBC in which case its a reflection about x = 0. I can fix that behavior. I will also have to fix rotations so they are done about the center of the lattice. This should be a quick fix.

Chris

2021-04-06 16:14 UTC, chrisrothUT commented
Bugs should be fixed

>>> import numpy as np
>>> g = nk.graph.Grid([3,3])
>>> r1 = g.space_group()[1]
>>> r1(np.arange(9)).reshape(3, 3)
array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])
>>> rquart = g.space_group()[2]
>>> rquart(np.arange(9)).reshape(3, 3)
array([[2, 5, 8],
       [1, 4, 7],
       [0, 3, 6]])

2021-04-07 10:45 UTC, femtobit commented
@chrisrothUT Yes, that helped.

One more thing: There is a bug with non-square directions (and the 1d chain) in rotations:
```python3
>>> nk.graph.Chain(8).rotations()
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
<ipython-input-16-b921bf637d7a> in <module>
----> 1 nk.graph.Chain(8).rotations()

~/repos/research/netket-pr/netket/graph/grid.py in rotations(self, period)
    276                 group = group @ self.planar_rotations(axes, period)
    277 
--> 278         return group
    279 
    280     def space_group(self) -> SymmGroup:

UnboundLocalError: local variable 'group' referenced before assignment
>>> nk.graph.Grid([4, 3]).rotations()
# [same error]
```
In both cases, the result should probably be only `[Identity()]`.

2021-04-07 16:06 UTC, chrisrothUT commented
Okay, I think I've fixed all of those issues. 

Anyway, I've tried all of the functions with a bunch of lattice shapes and different boundary conditions and haven't found any bugs

Sorry for all of these issues, I'm new to working on open source projects

2021-04-07 16:43 UTC, femtobit reviewed
@chrisrothUT Now worries, and thanks for the help! Now this looks pretty good to me.

I've just a couple more suggestions (some like `PlanarRotation.__repr__` are mostly matters of taste - feel free to apply or skip them as you like).

2021-04-07 16:43 UTC, femtobit commented on netket/graph/grid.py
> +            return f"R({self.num_quarter_rots}π/2,{self.axes}"
```suggestion
    def __repr__(self):
        return f"Rot({self.num_quarter_rots / 2:.1f}π, axes={self.axes})"
```
`Rot(0.5π, ...)`, `Rot(1.5π, ...)`, etc. all have the same width which can look be a bit more clean when printed.

2021-04-07 16:43 UTC, femtobit commented on netket/graph/grid.py
> +            return f"RF(0,{self.axis})"
`Reflection(reflect=False)` is the same as `Identity()`, so I think we should just skip that option.
```suggestion
@dataclass(frozen=True)
class Reflection(Element):
    axis: int
    dims: Tuple[int]

    def __call__(self, sites):
        sites = sites.reshape(self.dims)
        sites = _np.flip(sites, self.axis)
        return sites.ravel()

    def __repr__(self):
        return f"Ref(axis={self.axis})"
```

2021-04-07 16:43 UTC, femtobit commented on netket/graph/grid.py
> +    def axis_reflection(self, axis: int = 0) -> List[List[int]]:
```suggestion
    def axis_reflection(self, axis: int = 0) -> SymmGroup:
```

2021-04-07 16:43 UTC, femtobit commented on netket/graph/grid.py
> +        return SymmGroup([Identity()] + reflections, graph=self)
There is only ever one reflection when this is called with a specific axis, right? In that case, this should be simpler way of writing the same thing, if I\m not mistaken:
```suggestion
        dims = tuple(self.length)
        return SymmGroup([Identity(), Reflection(axis, dims)], graph=self)
```

2021-04-07 16:43 UTC, femtobit commented on netket/graph/grid.py
> +        Returns the full lattice grouup of a hypercube lattice
```suggestion
        Returns the full lattice symmetry group consisting of rotations, reflections, and periodic translation.
```
(I wouldn't say hypercube, as this works also for a rectangular shape now.)

2021-04-07 16:43 UTC, femtobit commented on netket/graph/grid.py
> +        Returns the full space grouup of a hypercube lattice
```suggestion
        Returns the full space group of the lattice.
```

2021-04-07 16:43 UTC, femtobit commented on netket/graph/grid.py
> +        Returns all possible rotations of a hypercube lattice
```suggestion
        Returns all possible rotation symmetries of the lattice.
```

2021-04-07 16:56 UTC, chrisrothUT commented
All of the suggestions looked good!

2021-04-07 16:58 UTC, femtobit approved these changes

2021-04-07 16:59 UTC, merged

2021-04-07 17:01 UTC, femtobit commented
Great. I've merged this into `symmetry-groups`, so we can get back to netket#600 now.

I'll go ahead and add `remove_duplicates` and a couple tests, then the space group part should be pretty much finished.

2021-04-07 17:10 UTC, chrisrothUT commented
Excellent, now I just need to add a function that computes the group algebra in SymmGroup and I can implement equivariant convolutions. This has been super helpful!